(ns notest.core)

(defn read-curr-test-src []
  (try
    ; TODO: no hardcoding
    (slurp "./test/notest/notest_autogen.clj")
    (catch Exception e
      (println "Could not read test file:" e)
      "")))

; 1 - namespace declaration
; 2 - the map of sterf
; 3 - the the deftest sucka
(defn structure-test [the-struct]
  {:namespace (first the-struct)
   :curr-tests (second the-struct)
   :testdef (get the-struct 2)})

(defn default-struct []
  ; TODO: no hardcoding
  {:namespace '(ns notest.autogen_test)
   :curr-tests '(def test-data {})
   :testdef '(deftest autogen
               (testing "Autogenerated"
                 (doseq [[func res] test-data]
                   (is (= (eval func) (eval res))))))})

(defmacro save-spec [the-expression]
  )

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
