(ns
 slothtest.autogen_test
 (:require [clojure.test :refer :all] [slothtest.core] [clojure.core]))

(def metadata {:apiversion 1})

(def
 test-data
 {'(clojure.core/+ 1 2 3 4) '10,
  '(slothtest.core/rjames 2) '4,
  '(clojure.core/* 1 2) '2,
  '(clojure.core// 1 2) '1/2,
  '(clojure.core/for [i [1 2 3]] (clojure.core/* 2 i)) '(2 4 6),
  '(clojure.core/+ 1 2) '3,
  '(clojure.core/+ 1 2 3) '6,
  '(slothtest.core/api-v1-to-v2
    {:curr-tests {'(clojure.core/+ 1 2) 3}, :metadata {:apiversion 1}})
  '{:metadata {:apiversion 2},
    :curr-tests [{:expression (clojure.core/+ 1 2), :result 3}]}})

(deftest
 autogen
 (testing
  "Autogenerated"
  (is (= (clojure.core/+ 1 2 3 4) '10))
  (is (= (slothtest.core/rjames 2) '4))
  (is (= (clojure.core/* 1 2) '2))
  (is (= (clojure.core// 1 2) '1/2))
  (is (= (clojure.core/for [i [1 2 3]] (clojure.core/* 2 i)) '(2 4 6)))
  (is (= (clojure.core/+ 1 2) '3))
  (is (= (clojure.core/+ 1 2 3) '6))
  (is
   (=
    (slothtest.core/api-v1-to-v2
     {:curr-tests {'(clojure.core/+ 1 2) 3},
      :metadata {:apiversion 1}})
    '{:metadata {:apiversion 2},
      :curr-tests [{:expression (clojure.core/+ 1 2), :result 3}]}))))
